#!/bin/bash

# profi'r adnabod geiriau'r lexicon y data hyfforddi yn unig. 
# test recognising words from the lexicon only.
#
HBuild wlist wordloop

HVite -A -D -T 1 -C config -H hmm15/hmmdefs -H hmm15/macros -i recout.mlf -w wordloop -t 250.0 150.0 3000.0 -p 0.0 -s 5.0 -S train.scp lexicon tiedlist

HResults -I words.mlf  tiedlist recout.mlf

