#!/bin/bash

mkdir -p hmm4 hmm5 hmm6 hmm7
cp hmm3/* hmm4

cp /usr/local/srdk/htk/sil.hed .

cd hmm4

cp /usr/local/srdk/htk/add_sp_to_hmmdefs_4.py .

python add_sp_to_hmmdefs_4.py

rm hmmdefs
mv hmmdefs-updated hmmdefs

rm add_sp_to_hmmdefs_4.py

cd - 

HHEd -A -D -T 1 -H hmm4/macros -H hmm4/hmmdefs -M hmm5 sil.hed monophones1

HERest -A -D -T 1 -C config  -I phones1.mlf -t 250.0 150.0 3000.0 -S train.scp -H hmm5/macros -H hmm5/hmmdefs -M hmm6 monophones1

HERest -A -D -T 1 -C config  -I phones1.mlf -t 250.0 150.0 3000.0 -S train.scp -H hmm6/macros -H hmm6/hmmdefs -M hmm7 monophones1
