#!/bin/bash

mkdir -p hmm0 hmm05 hmm1 hmm2 hmm3

cp /usr/local/srdk/htk/proto .
cp /usr/local/srdk/htk/config .

cp /usr/local/srdk/htk/make_pretrain_scp.py .

python make_pretrain_scp.py

HCompV -A -D -T 1 -C config -f 0.01 -m -S pretrain.scp -M hmm0 proto

rm make_pretrain_scp.py

cp monophones0 hmm0 
mv hmm0/monophones0 hmm0/hmmdefs
 
cd hmm0

cp /usr/local/srdk/htk/proto-hmmdefs .
cp /usr/local/srdk/htk/update_hmm0_hmmdefs.py .

python update_hmm0_hmmdefs.py

rm hmmdefs
rm proto-hmmdefs
rm update_hmm0_hmmdefs.py

mv hmmdefs-updated hmmdefs

head -3 proto > macros
cat vFloors >> macros 

cd -

cp /usr/local/srdk/htk/make_train_scp.py . 
rm -f train.scp
python make_train_scp.py
rm make_train_scp.py  

HERest -A -D -T 1 -C config -I phones0.mlf -t 250.0 150.0 1000.0 -S train.scp -H hmm0/macros -H hmm0/hmmdefs -M hmm1 monophones0

HERest -A -D -T 1 -C config -I phones0.mlf -t 250.0 150.0 1000.0 -S train.scp -H hmm1/macros -H hmm1/hmmdefs -M hmm2 monophones0

HERest -A -D -T 1 -C config -I phones0.mlf -t 250.0 150.0 1000.0 -S train.scp -H hmm2/macros -H hmm2/hmmdefs -M hmm3 monophones0

