#!/bin/bash
cp /usr/local/srdk/htk/global.ded .

cp /usr/local/srdk/htk/sort.py .
python sort.py lexicon
rm sort.py

cp /usr/local/srdk/htk/make_wlist.sh .
source make_wlist.sh
rm make_wlist.sh

HDMan -A -D -T 1 -m -w wlist -n monophones1 -i -l dlog dict lexicon

if ! grep -w "sil" monophones1; then
	echo "sil" >> monophones1
fi

sed '/sp/d' ./monophones1 > monophones0
cat dlog
